- name: Deploy disk logger script to slave
  hosts: slave
  become: yes

  tasks:
    - name: Copy logger script to remote
      copy:
        src: files/log_disk_usage.sh
        dest: /usr/local/bin/log_disk_usage.sh
        mode: '0755'

    - name: Copy systemd service file
      template:
        src: templates/logger.service.j2
        dest: /etc/systemd/system/logger.service
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start logger service
      systemd:
        name: logger.service
        enabled: yes
        state: started

    - name: Fetch log file to control machine
      tags: fetch_logs
      fetch:
        src: /var/log/disk_usage.log
        dest: ./logs/
        flat: yes
